"""update user
Revision ID: 26df2e3baf36
Revises: 70456e82871f
Create Date: 2021-11-05 20:15:47.370238
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26df2e3baf36'
down_revision = '70456e82871f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=50), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
