"""add class user
Revision ID: 70456e82871f
Revises: 
Create Date: 2021-11-05 19:35:19.675033
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70456e82871f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
